# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  driver: "imagick"

  filter_sets:
    thumb:
      quality: 75
      filters:
        thumbnail:
          size: [560, 330]
          mode: outbound
