language: node_js
node_js:
  - 14
services:
  - docker
install:
  - make vendor/autoload.php
script:
  - make lint
  - make test
cache:
  directories:
    - $HOME/.cache/yarn
    - $HOME/.composer/cache/files
