version: '3.1'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/var/www:delegated
      - ./tools/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony
  php:
    build:
      context: tools/docker/php
      args:
        TIMEZONE: ${TIMEZONE}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - .:/var/www:delegated
    environment:
      PHP_IDE_CONFIG: serverName=linkmat
    networks:
      - symfony
  db:
    image: postgres:12-alpine
    volumes:
      - db-data1:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: linkmat
      POSTGRES_USER: linkmat
      POSTGRES_DB: linkmat
      TZ: America/Toronto
      PGTZ: America/Toronto
    ports:
      - 5432:5432
    networks:
      - symfony
  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8888:8080
    networks:
      - symfony
  mail:
    image: mailhog/mailhog
    ports:
      - 1080:8025
  node:
    build:
      context: tools/docker/node
    command: yarn run dev
    working_dir: /usr/src/app
    user: '${USER_ID}:${GROUP_ID}'
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - symfony

volumes:
  db-data1:
    driver: local
  search-data:
    driver: local
networks:
  symfony:
