version: '3.3'
services:
  phptest:
    image: grafikart/php:1.0.3
    volumes:
      - .:/var/www:delegated
    links:
      - dbtest
  dbtest:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - 5433:5433
