# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  admin_prefix: '%env(resolve:ADMIN_PREFIX)%'
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Infrastructure/Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Http\Controller\:
    resource: '../src/Http/Controller/'
    tags: [ 'controller.service_arguments' ]
  App\Http\Admin\Controller\:
    resource: '../src/Http/Admin/Controller'
    tags: [ 'controller.service_arguments' ]
  App\Core\Twig\TwigAssetExtension:
    arguments:
      $assetPath: '%kernel.project_dir%/public/assets'
      $env: '%kernel.environment%'
